#lang racket
(define (Square)
  (display "Вычисление площади кольца")
  (newline)
  (display "Введите исходные данные:")
  (newline)
  (display "Радиус кольца (см) => ")
  (define kolco (read))
  (display "Радиус отверстия (см) => ")
  (define otverstie (read))
  (if (> otverstie kolco)
      (error "Ошибка! Радиус отверстия не может быть больше радиуса кольца.")
      (display (* 3.14 (- (* kolco kolco)(* otverstie otverstie))))
      )
  )

(define (Year)
  (display "Введите год:")
  (newline)
  (display "=> ")
  (define year (read))
  (display year)
  (if (= (modulo year 4) 0)
      (display " год - високосный")
      (display " год - не високосный")
      )
  )

(define (Resistance)
  (display "Вычисление сопротивления электрической цепи")
  (newline)
  (display "Введите исходные данные:")
  (newline)
  (display "Величина первого сопротивления (Ом) => ")
  (define r1 (read))
  (display "Величина второго сопротивления (Ом)=> ")
  (define r2 (read))
  (display "Тип соединения (1 - последовательное, 2 - параллельное) => ")
  (define type (read))
  (display "Сопротивление цепи: ")
  (if (or (> type 2)(< type 0))
      (error "Ошибка! Выберите корректный тип соединения!")
      (if (= type 1)
          (display (+ r1 r2))
          (display (/ (* r1 r2)(+ r1 r2)))
          )
      )
  )