#lang racket
(define (Volume)
  (display "Вычисление объема куба")
  (newline)
  (display "Введите длину ребра (см) и нажмите клавишу <Enter> = ")
  (define a (read))
  (display "Объем куба: ")
  (display (* a a a))
  (display " куб.см.")
  )

(define (Cost)
  (display "Вычисление стоимости покупки")
  (newline)
  (display "Введите исходные данные:")
  (newline)
  (display "Цена тетради (руб.) = ")
  (define ct (read))
  (display "Количество тетрадей = ")
  (define kt (read))
  (display "Цена карандаша (руб.) = ")
  (define ck (read))
  (display "Количество карандашей = ")
  (define kk (read))
  (display "Стоимость покупки: ")
  (display (+ (* ct kt)(* ck kk)))
  (display " руб.")
  )

(define (Apples)
  (display "Вычисление стоимости покупки")
  (newline)
  (display "Введите исходные данные:")
  (newline)
  (display "Цена одного килограмма яблок (руб.) = ")
  (define cena (read))
  (display "Вес яблок (кг) = ")
  (define ves (read))
  (display "Стоимость покупки: ")
  (display (* cena ves))
  (display " руб.")
  )